config/routes.rb
Rails.application.routes.draw do
	devise_for :admin_users, ActiveAdmin::Devise.config
	ActiveAdmin.routes(self)

	post "/(.:format)", to: "zhgivaleva#more"
	get  "/exhibitions", to: "zhgivaleva#exhibitions"
	get  "/about", to: "zhgivaleva#about"
	get  "/contact", to: "zhgivaleva#contact"

	root :to => "zhgivaleva#index"
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/exhibition.rb
class Exhibition < ActiveRecord::Base
end

app/models/image.rb
class Image < ActiveRecord::Base
end

app/models/material.rb
class Material < ActiveRecord::Base
	#
end

app/models/picture.rb
class Picture < ActiveRecord::Base
	belongs_to :tag
	belongs_to :image
	has_many :picture_materials
	has_many :materials, :through => :picture_materials
	accepts_nested_attributes_for :picture_materials, :allow_destroy => true
	accepts_nested_attributes_for :materials, :allow_destroy => true
	accepts_nested_attributes_for :image, :allow_destroy => true

	STORE_DIR = "upload"
	STORE_PATH = File.join("public", STORE_DIR)

	def file= file
		img_type = file.original_filename.split(".").last

		fname = DateTime.now.strftime("%Q") + '.' + img_type
		path = File.join(STORE_PATH, fname)

		File.open(path, "wb") { |f| f.write(file.read) }

		image_opt = ImageOptim.new
		image_opt.optimize_image!(path)

		sizes = FastImage.size(path)

		image = Image.new
		image.url = File.join("/", STORE_DIR, fname)
		image.name = file.original_filename
		image.width = sizes[0]
		image.height = sizes[1]
		image.size = File.size(path)
		image.save

		self.image_id = image.id
	end
end

app/models/picture_material.rb
class PictureMaterial < ActiveRecord::Base
	belongs_to :picture
	belongs_to :material
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	#
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :null_session
end

app/controllers/zhgivaleva_controller.rb
class ZhgivalevaController < ApplicationController

	Event = Struct.new(:day, :title, :place)
	MonthEvents = Struct.new(:name, :exhibitions)
	YearEvents = Struct.new(:name, :months)
	Painting = Struct.new(:tag, :title, :year, :materials, :url, :width, :height, :css)
	
	def index
		@tags = Tag.all
		pictures = Picture.all.limit(6)
		@paintings = Array.new

		pictures.each do |picture|
			ratio = picture.image.width.to_f / picture.image.height.to_f
			css = ""

			if ratio > 1.4
				css = "col-xs-12 col-sm-12 col-md-8 col-lg-6 col-el-4"
			else
				css = "col-xs-12 col-sm-6 col-md-4 col-lg-3 col-el-2"
			end

			@paintings.push(
				Painting.new(
					picture.tag.name,
					picture.title,
					picture.year,
					picture.materials.map { |material| material.title }.join(", "),
					picture.image.url,
					picture.width,
					picture.height,
					css
				)
			)
		end
	end

	def more
		offset = params[:offset].to_i
		limit = 6
		more = Picture.count - (offset + limit) > 0
		pictures = Picture.all.limit(limit).offset(offset)
		paintings = Array.new

		pictures.each do |picture|
			ratio = picture.image.width.to_f / picture.image.height.to_f
			css = ""

			if ratio > 1.4
				css = "col-xs-12 col-sm-12 col-md-8 col-lg-6 col-el-4"
			else
				css = "col-xs-12 col-sm-6 col-md-4 col-lg-3 col-el-2"
			end

			paintings.push(
				Painting.new(
					picture.tag.name,
					picture.title,
					picture.year,
					picture.materials.map { |material| material.title }.join(", "),
					picture.image.url,
					picture.width,
					picture.height,
					css
				)
			)
		end

		render json:
			Struct.new(:items, :more).new(paintings, more)
	end

	def exhibitions
		@events = Array.new
		exhibitions = Exhibition.all.order("date DESC")

		exhibitions.group_by{ |e| e.date.beginning_of_year }.each do |y, exs|
			months = Array.new
			
			exs.group_by{ |e| e.date.beginning_of_month }.each do |m, exs|
				events = Array.new

				exs.each do |e|
					events.push(
						Event.new(
							e.date.strftime("%d"),
							e.title,
							e.place
						)
					)
				end

				months.push(
					MonthEvents.new(
						m.strftime("%B"),
						events
					)
				)
			end
 
			@events.push(
				YearEvents.new(
					y.strftime("%Y"),
					months
				)
			)
		end

		puts @events
	end

	def about
		#
	end

	def contact
		#
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/zhgivaleva_helper.rb
module ZhgivalevaHelper
	#
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="shortcut icon" type="image/png" href="<%= image_path("favicon.png") %>"/>

	<title>Марина Жгивалёва</title>

	<%= csrf_meta_tags %>
</head>
<body>
	<div id="header">
		<div class="navbar">
			<div class="row">
				<div class="navbar-header">
					<a class="navbar-brand" href="/">
						<%= image_tag "logo.png", alt: "Zhgivaleva" %>
					</a>
					<div class="row">
						<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
							<span class="icon"></span>
						</button>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="navbar-collapse collapse" role="navigation">
					<ul class="nav navbar-nav">
						<li>
							<%= link_to content_tag(:span, "Работы", "data-title": "Работы"), root_path %>
						</li>
						<li>
							<%= link_to content_tag(:span, "Выставки", "data-title": "Выставки"), exhibitions_path %>
						</li>
						<li>
							<%= link_to content_tag(:span, "О себе", "data-title": "О себе"), about_path %>
						</li>
						<li>
							<%= link_to content_tag(:span, "Контакты", "data-title": "Контакты"), contact_path %>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>

	<%= yield %>

	<div id="footer">
		<div class="container">
			<div class="socials">
				<a class="icon vk" href="#"></a>
				<a class="icon fb" href="#"></a>
				<a class="icon ok" href="#"></a>
				<a class="icon tw" href="#"></a>
				<a class="icon gp" href="#"></a>
			</div>
			<div class="copyright">
				<span class="icon cr">©</span> <%= DateTime.now.strftime("%Y") %> Марина Жгивалёва
			</div>
		</div>
	</div>

	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/simple_captcha/_simple_captcha.erb
<div class="captcha">
	<div class="form-group">
		<%= simple_captcha_options[:image] %>
	</div>
	<div class="form-group">
		<%= simple_captcha_options[:field] %>
	</div>
</div>

app/views/zhgivaleva/about.html.erb
<div id="about" class="container equal-height">
	<div class="row">
		<div class="col col-xs-12 col-sm-6 hidden-xs left" style="background-image: url('<%= image_path("photo.jpg") %>')"></div>
		<div class="col col-xs-12 col-sm-6 right">
			<h1>
				Марина<br/>
				Жгивалёва
			</h1>

			<h5>художница</h5>

			<div class="separator light"></div>

			<p>1974г. Родилась в городе Рыбинске Ярославской области.</p>

			<p>1995г. окончила Ярославское Художественное Училище, отделение «Живопись».</p>
			
			<p>2001г. окончила Московский Государственный Университет Печати, факультет «Художественно-техническое оформление печатной продукции».</p>

			<p>2002г. член Союза Художников России.</p>

			<%= link_to "Связаться со мной", contact_path, :class=> "btn light" %>
		</div>
	</div>
</div>

app/views/zhgivaleva/contact.html.erb
<div id="contact" class="container equal-height">
	<div class="row">
		<div class="col col-sd-12 col-md-6 left">
			<div class="info-box">
				<span class="icon sl"></span>
				<div class="details">
					<h1>Ссылки</h1>
					<div class="separator light"></div>
					<div class="links">
						<p>
							<a class="icon fb" href="#"></a>
							<a class="link" href="#">facebook.com</a>
						</p>
						<p>
							<a class="icon fl" href="#"></a>
							<a class="link" href="#">flickr.com</a>
						</p>
						<p>
							<a class="icon da" href="#"></a>
							<a class="link" href="#">deviantart.com</a>
						</p>
						<p>
							<a class="icon be" href="#"></a>
							<a class="link" href="#">behance.net</a>
						</p>
						<p>
							<a class="icon li" href="#"></a>
							<a class="link" href="#">linkedin.com</a>
						</p>
					</div>
				</div>
			</div>
		</div>
		<div class="col col-sd-12 col-md-6 right">
			<h1>Написать</h1>

			<div class="separator light"></div>

			<%= form_tag(contact_path, method: "post") do %>
				<div class="form-group">
					<%= email_field_tag(:email, nil, placeholder: "Ваш e-mail", class: "form-control") %>
				</div>
				<div class="form-group">
					<%= text_field_tag(:title, nil, placeholder: "Заголовок", class: "form-control") %>
				</div>
				<div class="form-group">
					<%= text_area_tag(:text, "", size: "24x6", placeholder: "Сообщение", class: "form-control") %>
				</div>
				<%= show_simple_captcha(placeholder: "Код с картинки", input_html: { class: "form-control", maxlength: 4 }) %>
				<%= submit_tag("Отправить", class: "btn light") %>
			<% end %>
		</div>
	</div>
</div>

app/views/zhgivaleva/exhibitions.html.erb
<div id="exhibitions" class="container">
	<% @events.each do |year| %>
	<div class="row year">
		<h1><%= year.name %></h1>
		<div class="separator center"></div>
		<% year.months.each do |month| %>
		<div class="row month">
			<div class="col-md-6">
				<h2><%= I18n.t('date.month.' + month.name.downcase) %></h2>
			</div>
			<div class="col-md-6">
				<% month.exhibitions.each do |exhibition| %>
				<div class="row event">
					<h2 class="day"><%= exhibition.day %></h2>
					<p><%= exhibition.title %></p>
					<p class="place">/ <%= exhibition.place %> /</p>
				</div>
				<% end %>
			</div>
		</div>
		<% end %>
	</div>
	<% end %>
</div>

app/views/zhgivaleva/index.html.erb
<div id="portfolio" class=" container-fluid">
	<div id="portfolio" class=" container">
		<div class="separator center"></div>
		<ul class="filter nav nav-pills">
			<li class="active">
				<a href="#" class="active" data-group="all">Все</a>
			</li>
			<% @tags.each do |tag| %>
			<li>
				<a href="#" data-group="<%= tag.name %>"><%= tag.title %></a>
			</li>
			<% end %>
		</ul>
	</div>
	<div class="wrap">
		<% @paintings.each do |pic| %>
			<div class="item <%= pic.css %>" data-groups="<%= pic.tag %>">
				<a href="<%= pic.url %>" class="link" data-lightbox="picture" data-title="<%= pic.title %>">
					<div class="pic">
						<img src="<%= pic.url %>" alt="<%= pic.title %>"/>
					</div>
					<div class="cover">
						<h4><%= pic.title %></h4>
						<div class="info">
							<p><%= pic.materials %></p>
							<p><%= pic.width %>x<%= pic.height %>см</p>
							<p><%= pic.year %>г.</p>
						</div>
					</div>
				</a>
			</div>
		<% end %>
	</div>
	<div class="text-center">
		<a id="more" class="btn" href="#">Показать ещё</a>
	</div>
</div>
<script id="picture_tpl" type="text/x-jquery-tmpl">
	<div class="item ${css}" data-groups="${tag}">
		<a href="${url}" class="link" data-lightbox="picture" data-title="${title}">
			<div class="pic">
				<img src="${url}" alt="${title}"/>
			</div>
			<div class="cover">
				<h4>${title}</h4>
				<div class="info">
					<p>${materials}</p>
					<p>${width}x${height}см</p>
					<p>${year}г.</p>
				</div>
			</div>
		</a>
	</div>
</script>